<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;

class RWA_AddressDataSeeder extends Seeder
{
	/**
	 * Seed the application's database.
	 *
	 * @return void
	 */
	public function run()
	{
		$country_code = 'RWA';
        $created_at = datetime_db();

		DB::delete("delete from master_data where country_code ='RWA' and data_key in ('province', 'territory', 'district', 'sector', 'location') ");

		DB::table('master_data')->insert([

			// Province
			['country_code' => $country_code, 'data_key' => 'province', 'data_value' => 'Eastern Province', 'data_code' => 'eastern', 'parent_data_code' => null,  'status' => 'enabled', 'data_type' => 'common', 'created_at' => $created_at ],
			['country_code' => $country_code, 'data_key' => 'province', 'data_value' => 'Northern Province', 'data_code' => 'northern', 'parent_data_code' => null,  'status' => 'enabled', 'data_type' => 'common', 'created_at' => $created_at ],
			['country_code' => $country_code, 'data_key' => 'province', 'data_value' => 'Western Province', 'data_code' => 'western', 'parent_data_code' => null,  'status' => 'enabled', 'data_type' => 'common', 'created_at' => $created_at ],
			['country_code' => $country_code, 'data_key' => 'province', 'data_value' => 'Southern Province', 'data_code' => 'southern', 'parent_data_code' => null,  'status' => 'enabled', 'data_type' => 'common', 'created_at' => $created_at ],
			['country_code' => $country_code, 'data_key' => 'province', 'data_value' => 'Kigali', 'data_code' => 'kigali', 'parent_data_code' => null,  'status' => 'enabled', 'data_type' => 'common', 'created_at' => $created_at ],

			// District
			['country_code' => $country_code, 'data_key' => 'district', 'data_value' => 'Nyagatare', 'data_code' => 'nyagatare', 'parent_data_code' => 'eastern',  'status' => 'enabled', 'data_type' => 'common', 'created_at' => $created_at ],
			['country_code' => $country_code, 'data_key' => 'district', 'data_value' => 'Gatsibo', 'data_code' => 'gatsibo', 'parent_data_code' => 'eastern',  'status' => 'enabled', 'data_type' => 'common', 'created_at' => $created_at ],
			['country_code' => $country_code, 'data_key' => 'district', 'data_value' => 'Bugesera', 'data_code' => 'bugesera', 'parent_data_code' => 'eastern',  'status' => 'enabled', 'data_type' => 'common', 'created_at' => $created_at ],
			['country_code' => $country_code, 'data_key' => 'district', 'data_value' => 'Kayonza', 'data_code' => 'kayonza', 'parent_data_code' => 'eastern',  'status' => 'enabled', 'data_type' => 'common', 'created_at' => $created_at ],
			['country_code' => $country_code, 'data_key' => 'district', 'data_value' => 'Ngoma', 'data_code' => 'ngoma', 'parent_data_code' => 'eastern',  'status' => 'enabled', 'data_type' => 'common', 'created_at' => $created_at ],
			['country_code' => $country_code, 'data_key' => 'district', 'data_value' => 'Kirehe', 'data_code' => 'kirehe', 'parent_data_code' => 'eastern',  'status' => 'enabled', 'data_type' => 'common', 'created_at' => $created_at ],
			['country_code' => $country_code, 'data_key' => 'district', 'data_value' => 'Rwamagana', 'data_code' => 'rwamagana', 'parent_data_code' => 'eastern',  'status' => 'enabled', 'data_type' => 'common', 'created_at' => $created_at ],

			['country_code' => $country_code, 'data_key' => 'district', 'data_value' => 'Burera', 'data_code' => 'burera', 'parent_data_code' => 'northern',  'status' => 'enabled', 'data_type' => 'common', 'created_at' => $created_at ],
			['country_code' => $country_code, 'data_key' => 'district', 'data_value' => 'Gakenke', 'data_code' => 'gakenke', 'parent_data_code' => 'northern',  'status' => 'enabled', 'data_type' => 'common', 'created_at' => $created_at ],
			['country_code' => $country_code, 'data_key' => 'district', 'data_value' => 'Gicumbi', 'data_code' => 'gicumbi', 'parent_data_code' => 'northern',  'status' => 'enabled', 'data_type' => 'common', 'created_at' => $created_at ],
			['country_code' => $country_code, 'data_key' => 'district', 'data_value' => 'Musanze', 'data_code' => 'musanze', 'parent_data_code' => 'northern',  'status' => 'enabled', 'data_type' => 'common', 'created_at' => $created_at ],
			['country_code' => $country_code, 'data_key' => 'district', 'data_value' => 'Rulindo', 'data_code' => 'rulindo', 'parent_data_code' => 'northern',  'status' => 'enabled', 'data_type' => 'common', 'created_at' => $created_at ],

			['country_code' => $country_code, 'data_key' => 'district', 'data_value' => 'Karongi', 'data_code' => 'karongi', 'parent_data_code' => 'western',  'status' => 'enabled', 'data_type' => 'common', 'created_at' => $created_at ],
			['country_code' => $country_code, 'data_key' => 'district', 'data_value' => 'Ngororero', 'data_code' => 'ngororero', 'parent_data_code' => 'western',  'status' => 'enabled', 'data_type' => 'common', 'created_at' => $created_at ],
			['country_code' => $country_code, 'data_key' => 'district', 'data_value' => 'Nyabihu', 'data_code' => 'nyabihu', 'parent_data_code' => 'western',  'status' => 'enabled', 'data_type' => 'common', 'created_at' => $created_at ],
			['country_code' => $country_code, 'data_key' => 'district', 'data_value' => 'Nyamasheke', 'data_code' => 'nyamasheke', 'parent_data_code' => 'western',  'status' => 'enabled', 'data_type' => 'common', 'created_at' => $created_at ],

			['country_code' => $country_code, 'data_key' => 'district', 'data_value' => 'Muhanga', 'data_code' => 'muhanga', 'parent_data_code' => 'southern',  'status' => 'enabled', 'data_type' => 'common', 'created_at' => $created_at ],
			['country_code' => $country_code, 'data_key' => 'district', 'data_value' => 'Nyamagabe', 'data_code' => 'nyamagabe', 'parent_data_code' => 'southern',  'status' => 'enabled', 'data_type' => 'common', 'created_at' => $created_at ],
			['country_code' => $country_code, 'data_key' => 'district', 'data_value' => 'Nyanza', 'data_code' => 'nyanza', 'parent_data_code' => 'southern',  'status' => 'enabled', 'data_type' => 'common', 'created_at' => $created_at ],
			['country_code' => $country_code, 'data_key' => 'district', 'data_value' => 'Nyaruguru', 'data_code' => 'nyaruguru', 'parent_data_code' => 'southern',  'status' => 'enabled', 'data_type' => 'common', 'created_at' => $created_at ],
			['country_code' => $country_code, 'data_key' => 'district', 'data_value' => 'Ruhango', 'data_code' => 'ruhango', 'parent_data_code' => 'southern',  'status' => 'enabled', 'data_type' => 'common', 'created_at' => $created_at ],

			['country_code' => $country_code, 'data_key' => 'district', 'data_value' => 'Gasabo', 'data_code' => 'gasabo', 'parent_data_code' => 'kigali',  'status' => 'enabled', 'data_type' => 'common', 'created_at' => $created_at ],
			['country_code' => $country_code, 'data_key' => 'district', 'data_value' => 'Kicukiro', 'data_code' => 'kicukiro', 'parent_data_code' => 'kigali',  'status' => 'enabled', 'data_type' => 'common', 'created_at' => $created_at ],
			['country_code' => $country_code, 'data_key' => 'district', 'data_value' => 'Nyarugenge', 'data_code' => 'nyarugenge', 'parent_data_code' => 'kigali',  'status' => 'enabled', 'data_type' => 'common', 'created_at' => $created_at ],

			// Sector
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rwimiyaga', 'data_code' =>'rwimiyaga', 'parent_data_code' =>'nyagatare' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Karangazi', 'data_code' =>'karangazi', 'parent_data_code' =>'nyagatare' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Nyagatare', 'data_code' =>'nyagatare', 'parent_data_code' =>'nyagatare' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Katabagemu', 'data_code' =>'katabagemu', 'parent_data_code' =>'nyagatare' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rukomo', 'data_code' =>'rukomo', 'parent_data_code' =>'nyagatare' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Tabagwe', 'data_code' =>'tabagwe', 'parent_data_code' =>'nyagatare' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Musheli', 'data_code' =>'musheli', 'parent_data_code' =>'nyagatare' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Gatunda', 'data_code' =>'gatunda', 'parent_data_code' =>'nyagatare' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Mimuli', 'data_code' =>'mimuli', 'parent_data_code' =>'nyagatare' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Karama', 'data_code' =>'karama', 'parent_data_code' =>'nyagatare' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Matimba', 'data_code' =>'matimba', 'parent_data_code' =>'nyagatare' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Mukama', 'data_code' =>'mukama', 'parent_data_code' =>'nyagatare' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rwempasha', 'data_code' =>'rwempasha', 'parent_data_code' =>'nyagatare' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kiyombe', 'data_code' =>'kiyombe', 'parent_data_code' =>'nyagatare' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],

			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Gasange', 'data_code' =>'gasange', 'parent_data_code' =>'gatsibo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Gatsibo', 'data_code' =>'gatsibo', 'parent_data_code' =>'gatsibo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Gitoki', 'data_code' =>'gitoki', 'parent_data_code' =>'gatsibo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kabarore', 'data_code' =>'kabarore', 'parent_data_code' =>'gatsibo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kageyo', 'data_code' =>'kageyo', 'parent_data_code' =>'gatsibo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kiramuruzi', 'data_code' =>'kiramuruzi', 'parent_data_code' =>'gatsibo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kiziguro', 'data_code' =>'kiziguro', 'parent_data_code' =>'gatsibo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Muhura', 'data_code' =>'muhura', 'parent_data_code' =>'gatsibo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Murambi', 'data_code' =>'murambi', 'parent_data_code' =>'gatsibo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Ngarama', 'data_code' =>'ngarama', 'parent_data_code' =>'gatsibo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Nyagihanga', 'data_code' =>'nyagihanga', 'parent_data_code' =>'gatsibo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Remera', 'data_code' =>'remera', 'parent_data_code' =>'gatsibo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rugarama', 'data_code' =>'rugarama', 'parent_data_code' =>'gatsibo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rwimbogo', 'data_code' =>'rwimbogo', 'parent_data_code' =>'gatsibo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],

			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Gashora', 'data_code' =>'gashora', 'parent_data_code' =>'bugesera' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Juru', 'data_code' =>'juru', 'parent_data_code' =>'bugesera' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kamabuye', 'data_code' =>'kamabuye', 'parent_data_code' =>'bugesera' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Ntarama', 'data_code' =>'ntarama', 'parent_data_code' =>'bugesera' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Mareba', 'data_code' =>'mareba', 'parent_data_code' =>'bugesera' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Mayange', 'data_code' =>'mayange', 'parent_data_code' =>'bugesera' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Musenyi', 'data_code' =>'musenyi', 'parent_data_code' =>'bugesera' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Mwogo', 'data_code' =>'mwogo', 'parent_data_code' =>'bugesera' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Ngeruka', 'data_code' =>'ngeruka', 'parent_data_code' =>'bugesera' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Nyamata', 'data_code' =>'nyamata', 'parent_data_code' =>'bugesera' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Nyarugenge', 'data_code' =>'nyarugenge', 'parent_data_code' =>'bugesera' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rilima', 'data_code' =>'rilima', 'parent_data_code' =>'bugesera' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Ruhuha', 'data_code' =>'ruhuha', 'parent_data_code' =>'bugesera' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rweru', 'data_code' =>'rweru', 'parent_data_code' =>'bugesera' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Shyara', 'data_code' =>'shyara', 'parent_data_code' =>'bugesera' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],

			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Gahini', 'data_code' =>'gahini', 'parent_data_code' =>'kayonza' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kabare', 'data_code' =>'kabare', 'parent_data_code' =>'kayonza' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kabarondo', 'data_code' =>'kabarondo', 'parent_data_code' =>'kayonza' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Mukarange', 'data_code' =>'mukarange', 'parent_data_code' =>'kayonza' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Murama', 'data_code' =>'murama', 'parent_data_code' =>'kayonza' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Murundi', 'data_code' =>'murundi', 'parent_data_code' =>'kayonza' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Mwiri', 'data_code' =>'mwiri', 'parent_data_code' =>'kayonza' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Ndego', 'data_code' =>'ndego', 'parent_data_code' =>'kayonza' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Nyamirama', 'data_code' =>'nyamirama', 'parent_data_code' =>'kayonza' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rukara', 'data_code' =>'rukara', 'parent_data_code' =>'kayonza' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Ruramira', 'data_code' =>'ruramira', 'parent_data_code' =>'kayonza' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rwinkwavu', 'data_code' =>'rwinkwavu', 'parent_data_code' =>'kayonza' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],

			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Gashanda', 'data_code' =>'gashanda', 'parent_data_code' =>'ngoma' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Jarama', 'data_code' =>'jarama', 'parent_data_code' =>'ngoma' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Karembo', 'data_code' =>'karembo', 'parent_data_code' =>'ngoma' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kazo', 'data_code' =>'kazo', 'parent_data_code' =>'ngoma' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kibungo', 'data_code' =>'kibungo', 'parent_data_code' =>'ngoma' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Mugesera', 'data_code' =>'mugesera', 'parent_data_code' =>'ngoma' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Murama', 'data_code' =>'murama', 'parent_data_code' =>'ngoma' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Mutenderi', 'data_code' =>'mutenderi', 'parent_data_code' =>'ngoma' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Remera', 'data_code' =>'remera', 'parent_data_code' =>'ngoma' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rukira', 'data_code' =>'rukira', 'parent_data_code' =>'ngoma' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rukumberi', 'data_code' =>'rukumberi', 'parent_data_code' =>'ngoma' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rurenge', 'data_code' =>'rurenge', 'parent_data_code' =>'ngoma' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Sake', 'data_code' =>'sake', 'parent_data_code' =>'ngoma' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Zaza', 'data_code' =>'zaza', 'parent_data_code' =>'ngoma' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],

			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Gahara', 'data_code' =>'gahara', 'parent_data_code' =>'kirehe' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Gatore', 'data_code' =>'gatore', 'parent_data_code' =>'kirehe' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kigarama', 'data_code' =>'kigarama', 'parent_data_code' =>'kirehe' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kigina', 'data_code' =>'kigina', 'parent_data_code' =>'kirehe' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kirehe', 'data_code' =>'kirehe', 'parent_data_code' =>'kirehe' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Mahama', 'data_code' =>'mahama', 'parent_data_code' =>'kirehe' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Mpanga', 'data_code' =>'mpanga', 'parent_data_code' =>'kirehe' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Musaza', 'data_code' =>'musaza', 'parent_data_code' =>'kirehe' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Mushikiri', 'data_code' =>'mushikiri', 'parent_data_code' =>'kirehe' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Nasho', 'data_code' =>'nasho', 'parent_data_code' =>'kirehe' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Nyamugari', 'data_code' =>'nyamugari', 'parent_data_code' =>'kirehe' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Nyarubuye', 'data_code' =>'nyarubuye', 'parent_data_code' =>'kirehe' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],

			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Fumbwe', 'data_code' =>'fumbwe', 'parent_data_code' =>'rwamagana' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Gahengeri', 'data_code' =>'gahengeri', 'parent_data_code' =>'rwamagana' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Gishari', 'data_code' =>'gishari', 'parent_data_code' =>'rwamagana' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Karenge', 'data_code' =>'karenge', 'parent_data_code' =>'rwamagana' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kigabiro', 'data_code' =>'kigabiro', 'parent_data_code' =>'rwamagana' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Muhazi', 'data_code' =>'muhazi', 'parent_data_code' =>'rwamagana' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Munyaga', 'data_code' =>'munyaga', 'parent_data_code' =>'rwamagana' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Munyiginya', 'data_code' =>'munyiginya', 'parent_data_code' =>'rwamagana' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Musha', 'data_code' =>'musha', 'parent_data_code' =>'rwamagana' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Muyumbu', 'data_code' =>'muyumbu', 'parent_data_code' =>'rwamagana' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Mwulire', 'data_code' =>'mwulire', 'parent_data_code' =>'rwamagana' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Nyakariro', 'data_code' =>'nyakariro', 'parent_data_code' =>'rwamagana' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Nzige', 'data_code' =>'nzige', 'parent_data_code' =>'rwamagana' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rubona', 'data_code' =>'rubona', 'parent_data_code' =>'rwamagana' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],

			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Bungwe', 'data_code' =>'bungwe', 'parent_data_code' =>'burera' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Butaro', 'data_code' =>'butaro', 'parent_data_code' =>'burera' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Cyanika', 'data_code' =>'cyanika', 'parent_data_code' =>'burera' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Cyeru', 'data_code' =>'cyeru', 'parent_data_code' =>'burera' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Gahunga', 'data_code' =>'gahunga', 'parent_data_code' =>'burera' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Gatebe', 'data_code' =>'gatebe', 'parent_data_code' =>'burera' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Gitovu', 'data_code' =>'gitovu', 'parent_data_code' =>'burera' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kagogo', 'data_code' =>'kagogo', 'parent_data_code' =>'burera' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kinoni', 'data_code' =>'kinoni', 'parent_data_code' =>'burera' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kinyababa', 'data_code' =>'kinyababa', 'parent_data_code' =>'burera' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kivuye', 'data_code' =>'kivuye', 'parent_data_code' =>'burera' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Nemba', 'data_code' =>'nemba', 'parent_data_code' =>'burera' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rugarama', 'data_code' =>'rugarama', 'parent_data_code' =>'burera' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rugendabari', 'data_code' =>'rugendabari', 'parent_data_code' =>'burera' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Ruhunde', 'data_code' =>'ruhunde', 'parent_data_code' =>'burera' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rusarabuye', 'data_code' =>'rusarabuye', 'parent_data_code' =>'burera' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rwerere', 'data_code' =>'rwerere', 'parent_data_code' =>'burera' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],

			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Busengo', 'data_code' =>'busengo', 'parent_data_code' =>'gakenke' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Coko', 'data_code' =>'coko', 'parent_data_code' =>'gakenke' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Cyabingo', 'data_code' =>'cyabingo', 'parent_data_code' =>'gakenke' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Gakenke', 'data_code' =>'gakenke', 'parent_data_code' =>'gakenke' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Gashenyi', 'data_code' =>'gashenyi', 'parent_data_code' =>'gakenke' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Mugunga', 'data_code' =>'mugunga', 'parent_data_code' =>'gakenke' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Janja', 'data_code' =>'janja', 'parent_data_code' =>'gakenke' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kamubuga', 'data_code' =>'kamubuga', 'parent_data_code' =>'gakenke' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Karambo', 'data_code' =>'karambo', 'parent_data_code' =>'gakenke' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kivuruga', 'data_code' =>'kivuruga', 'parent_data_code' =>'gakenke' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Mataba', 'data_code' =>'mataba', 'parent_data_code' =>'gakenke' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Minazi', 'data_code' =>'minazi', 'parent_data_code' =>'gakenke' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Muhondo', 'data_code' =>'muhondo', 'parent_data_code' =>'gakenke' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Muyongwe', 'data_code' =>'muyongwe', 'parent_data_code' =>'gakenke' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Muzo', 'data_code' =>'muzo', 'parent_data_code' =>'gakenke' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rusasa', 'data_code' =>'rusasa', 'parent_data_code' =>'gakenke' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rushashi', 'data_code' =>'rushashi', 'parent_data_code' =>'gakenke' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Nemba', 'data_code' =>'nemba', 'parent_data_code' =>'gakenke' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],

			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Bukure', 'data_code' =>'bukure', 'parent_data_code' =>'gicumbi' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Bwisige', 'data_code' =>'bwisige', 'parent_data_code' =>'gicumbi' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Byumba', 'data_code' =>'byumba', 'parent_data_code' =>'gicumbi' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Cyumba', 'data_code' =>'cyumba', 'parent_data_code' =>'gicumbi' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Giti', 'data_code' =>'giti', 'parent_data_code' =>'gicumbi' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kaniga', 'data_code' =>'kaniga', 'parent_data_code' =>'gicumbi' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Miyove', 'data_code' =>'miyove', 'parent_data_code' =>'gicumbi' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kageyo', 'data_code' =>'kageyo', 'parent_data_code' =>'gicumbi' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Mukarange', 'data_code' =>'mukarange', 'parent_data_code' =>'gicumbi' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Manyagiro', 'data_code' =>'manyagiro', 'parent_data_code' =>'gicumbi' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Muko', 'data_code' =>'muko', 'parent_data_code' =>'gicumbi' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Mutete', 'data_code' =>'mutete', 'parent_data_code' =>'gicumbi' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Nyamiyaga', 'data_code' =>'nyamiyaga', 'parent_data_code' =>'gicumbi' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Nyankenke II', 'data_code' =>'nyankenke ii', 'parent_data_code' =>'gicumbi' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rubaya', 'data_code' =>'rubaya', 'parent_data_code' =>'gicumbi' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rukomo', 'data_code' =>'rukomo', 'parent_data_code' =>'gicumbi' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rushaki', 'data_code' =>'rushaki', 'parent_data_code' =>'gicumbi' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rutare', 'data_code' =>'rutare', 'parent_data_code' =>'gicumbi' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Ruvune', 'data_code' =>'ruvune', 'parent_data_code' =>'gicumbi' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rwamiko', 'data_code' =>'rwamiko', 'parent_data_code' =>'gicumbi' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Shangasha', 'data_code' =>'shangasha', 'parent_data_code' =>'gicumbi' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],

			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Busogo', 'data_code' =>'busogo', 'parent_data_code' =>'musanze' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Cyuve', 'data_code' =>'cyuve', 'parent_data_code' =>'musanze' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Gacaca', 'data_code' =>'gacaca', 'parent_data_code' =>'musanze' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Gashaki', 'data_code' =>'gashaki', 'parent_data_code' =>'musanze' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Gataraga', 'data_code' =>'gataraga', 'parent_data_code' =>'musanze' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kimonyi', 'data_code' =>'kimonyi', 'parent_data_code' =>'musanze' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kinigi', 'data_code' =>'kinigi', 'parent_data_code' =>'musanze' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Muhoza', 'data_code' =>'muhoza', 'parent_data_code' =>'musanze' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Muko', 'data_code' =>'muko', 'parent_data_code' =>'musanze' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Musanze', 'data_code' =>'musanze', 'parent_data_code' =>'musanze' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Nkotsi', 'data_code' =>'nkotsi', 'parent_data_code' =>'musanze' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Nyange', 'data_code' =>'nyange', 'parent_data_code' =>'musanze' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Remera', 'data_code' =>'remera', 'parent_data_code' =>'musanze' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Shingiro', 'data_code' =>'shingiro', 'parent_data_code' =>'musanze' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],

			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Base', 'data_code' =>'base', 'parent_data_code' =>'rulindo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Burega', 'data_code' =>'burega', 'parent_data_code' =>'rulindo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Bushoki', 'data_code' =>'bushoki', 'parent_data_code' =>'rulindo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Buyoga', 'data_code' =>'buyoga', 'parent_data_code' =>'rulindo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Cyinzuzi', 'data_code' =>'cyinzuzi', 'parent_data_code' =>'rulindo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Cyungo', 'data_code' =>'cyungo', 'parent_data_code' =>'rulindo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kinihira', 'data_code' =>'kinihira', 'parent_data_code' =>'rulindo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kisaro', 'data_code' =>'kisaro', 'parent_data_code' =>'rulindo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Masoro', 'data_code' =>'masoro', 'parent_data_code' =>'rulindo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Mbogo', 'data_code' =>'mbogo', 'parent_data_code' =>'rulindo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Murambi', 'data_code' =>'murambi', 'parent_data_code' =>'rulindo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Ngoma', 'data_code' =>'ngoma', 'parent_data_code' =>'rulindo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Ntarabana', 'data_code' =>'ntarabana', 'parent_data_code' =>'rulindo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rukozo', 'data_code' =>'rukozo', 'parent_data_code' =>'rulindo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rusiga', 'data_code' =>'rusiga', 'parent_data_code' =>'rulindo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Shyorongi', 'data_code' =>'shyorongi', 'parent_data_code' =>'rulindo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Tumba', 'data_code' =>'tumba', 'parent_data_code' =>'rulindo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],

			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Bwishyura', 'data_code' =>'bwishyura', 'parent_data_code' =>'karongi' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Gashyita', 'data_code' =>'gashyita', 'parent_data_code' =>'karongi' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Gishari', 'data_code' =>'gishari', 'parent_data_code' =>'karongi' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Gitesi', 'data_code' =>'gitesi', 'parent_data_code' =>'karongi' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Mubuga', 'data_code' =>'mubuga', 'parent_data_code' =>'karongi' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Murambi', 'data_code' =>'murambi', 'parent_data_code' =>'karongi' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Mutuntu', 'data_code' =>'mutuntu', 'parent_data_code' =>'karongi' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Murundi', 'data_code' =>'murundi', 'parent_data_code' =>'karongi' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rubengera', 'data_code' =>'rubengera', 'parent_data_code' =>'karongi' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rugabana', 'data_code' =>'rugabana', 'parent_data_code' =>'karongi' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rugando', 'data_code' =>'rugando', 'parent_data_code' =>'karongi' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rwankuba', 'data_code' =>'rwankuba', 'parent_data_code' =>'karongi' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Twumba', 'data_code' =>'twumba', 'parent_data_code' =>'karongi' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],

			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Bwira', 'data_code' =>'bwira', 'parent_data_code' =>'ngororero' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Gatumba', 'data_code' =>'gatumba', 'parent_data_code' =>'ngororero' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Hindiro', 'data_code' =>'hindiro', 'parent_data_code' =>'ngororero' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kabaya', 'data_code' =>'kabaya', 'parent_data_code' =>'ngororero' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kageyo', 'data_code' =>'kageyo', 'parent_data_code' =>'ngororero' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kavumu', 'data_code' =>'kavumu', 'parent_data_code' =>'ngororero' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Matyazo', 'data_code' =>'matyazo', 'parent_data_code' =>'ngororero' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Muhanda', 'data_code' =>'muhanda', 'parent_data_code' =>'ngororero' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Muhororo', 'data_code' =>'muhororo', 'parent_data_code' =>'ngororero' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Ndaro', 'data_code' =>'ndaro', 'parent_data_code' =>'ngororero' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Ngororero', 'data_code' =>'ngororero', 'parent_data_code' =>'ngororero' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Nyange', 'data_code' =>'nyange', 'parent_data_code' =>'ngororero' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Sovu', 'data_code' =>'sovu', 'parent_data_code' =>'ngororero' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],

			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Bigogwe', 'data_code' =>'bigogwe', 'parent_data_code' =>'nyabihu' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Jenda', 'data_code' =>'jenda', 'parent_data_code' =>'nyabihu' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Jomba', 'data_code' =>'jomba', 'parent_data_code' =>'nyabihu' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kabatwa', 'data_code' =>'kabatwa', 'parent_data_code' =>'nyabihu' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Karago', 'data_code' =>'karago', 'parent_data_code' =>'nyabihu' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kintobo', 'data_code' =>'kintobo', 'parent_data_code' =>'nyabihu' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Mukamira', 'data_code' =>'mukamira', 'parent_data_code' =>'nyabihu' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Muringa', 'data_code' =>'muringa', 'parent_data_code' =>'nyabihu' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rambura', 'data_code' =>'rambura', 'parent_data_code' =>'nyabihu' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rugera', 'data_code' =>'rugera', 'parent_data_code' =>'nyabihu' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rurembo', 'data_code' =>'rurembo', 'parent_data_code' =>'nyabihu' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Shyira', 'data_code' =>'shyira', 'parent_data_code' =>'nyabihu' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],

			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Ruharambuga', 'data_code' =>'ruharambuga', 'parent_data_code' =>'nyamasheke' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Bushekeri', 'data_code' =>'bushekeri', 'parent_data_code' =>'nyamasheke' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Bushenge', 'data_code' =>'bushenge', 'parent_data_code' =>'nyamasheke' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Cyato', 'data_code' =>'cyato', 'parent_data_code' =>'nyamasheke' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Gihombo', 'data_code' =>'gihombo', 'parent_data_code' =>'nyamasheke' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kagano', 'data_code' =>'kagano', 'parent_data_code' =>'nyamasheke' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kanjongo', 'data_code' =>'kanjongo', 'parent_data_code' =>'nyamasheke' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Karambi', 'data_code' =>'karambi', 'parent_data_code' =>'nyamasheke' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Karengera', 'data_code' =>'karengera', 'parent_data_code' =>'nyamasheke' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kirimbi', 'data_code' =>'kirimbi', 'parent_data_code' =>'nyamasheke' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Macuba', 'data_code' =>'macuba', 'parent_data_code' =>'nyamasheke' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Nyabitekeri', 'data_code' =>'nyabitekeri', 'parent_data_code' =>'nyamasheke' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Mahembe', 'data_code' =>'mahembe', 'parent_data_code' =>'nyamasheke' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rangiro', 'data_code' =>'rangiro', 'parent_data_code' =>'nyamasheke' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Shangi', 'data_code' =>'shangi', 'parent_data_code' =>'nyamasheke' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],

			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Nyamabuye', 'data_code' =>'nyamabuye', 'parent_data_code' =>'muhanga' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Shyogwe', 'data_code' =>'shyogwe', 'parent_data_code' =>'muhanga' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Cyeza', 'data_code' =>'cyeza', 'parent_data_code' =>'muhanga' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rugendabari', 'data_code' =>'rugendabari', 'parent_data_code' =>'muhanga' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Nyabinoni', 'data_code' =>'nyabinoni', 'parent_data_code' =>'muhanga' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Nyarusange', 'data_code' =>'nyarusange', 'parent_data_code' =>'muhanga' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rongi', 'data_code' =>'rongi', 'parent_data_code' =>'muhanga' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kabacuzi', 'data_code' =>'kabacuzi', 'parent_data_code' =>'muhanga' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'KIBANGU', 'data_code' =>'kibangu', 'parent_data_code' =>'muhanga' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kiyumba', 'data_code' =>'kiyumba', 'parent_data_code' =>'muhanga' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'MUSHISHIRO', 'data_code' =>'mushishiro', 'parent_data_code' =>'muhanga' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Muhanga', 'data_code' =>'muhanga', 'parent_data_code' =>'muhanga' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],

			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Buruhukiro', 'data_code' =>'buruhukiro', 'parent_data_code' =>'nyamagabe' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Cyanika', 'data_code' =>'cyanika', 'parent_data_code' =>'nyamagabe' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Gatare', 'data_code' =>'gatare', 'parent_data_code' =>'nyamagabe' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kaduha', 'data_code' =>'kaduha', 'parent_data_code' =>'nyamagabe' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kamegeri', 'data_code' =>'kamegeri', 'parent_data_code' =>'nyamagabe' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kibirizi', 'data_code' =>'kibirizi', 'parent_data_code' =>'nyamagabe' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kibumbwe', 'data_code' =>'kibumbwe', 'parent_data_code' =>'nyamagabe' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kitabi', 'data_code' =>'kitabi', 'parent_data_code' =>'nyamagabe' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Mbazi', 'data_code' =>'mbazi', 'parent_data_code' =>'nyamagabe' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Mugano', 'data_code' =>'mugano', 'parent_data_code' =>'nyamagabe' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Musange', 'data_code' =>'musange', 'parent_data_code' =>'nyamagabe' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Musebeya', 'data_code' =>'musebeya', 'parent_data_code' =>'nyamagabe' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Mishubi', 'data_code' =>'mishubi', 'parent_data_code' =>'nyamagabe' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Nkomane', 'data_code' =>'nkomane', 'parent_data_code' =>'nyamagabe' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Gasaka', 'data_code' =>'gasaka', 'parent_data_code' =>'nyamagabe' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Tare', 'data_code' =>'tare', 'parent_data_code' =>'nyamagabe' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Uwinkingi', 'data_code' =>'uwinkingi', 'parent_data_code' =>'nyamagabe' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],

			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Busasamana', 'data_code' =>'busasamana', 'parent_data_code' =>'nyanza' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Busororo', 'data_code' =>'busororo', 'parent_data_code' =>'nyanza' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Cyabakamyi', 'data_code' =>'cyabakamyi', 'parent_data_code' =>'nyanza' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kibirizi', 'data_code' =>'kibirizi', 'parent_data_code' =>'nyanza' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kigoma', 'data_code' =>'kigoma', 'parent_data_code' =>'nyanza' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Mukingo', 'data_code' =>'mukingo', 'parent_data_code' =>'nyanza' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Muyira', 'data_code' =>'muyira', 'parent_data_code' =>'nyanza' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Ntyazo', 'data_code' =>'ntyazo', 'parent_data_code' =>'nyanza' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Nyagisozi', 'data_code' =>'nyagisozi', 'parent_data_code' =>'nyanza' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rwabicuma', 'data_code' =>'rwabicuma', 'parent_data_code' =>'nyanza' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],

			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Cyahinda', 'data_code' =>'cyahinda', 'parent_data_code' =>'nyaruguru' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Busanze', 'data_code' =>'busanze', 'parent_data_code' =>'nyaruguru' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kibeho', 'data_code' =>'kibeho', 'parent_data_code' =>'nyaruguru' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Mata', 'data_code' =>'mata', 'parent_data_code' =>'nyaruguru' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Munini', 'data_code' =>'munini', 'parent_data_code' =>'nyaruguru' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kivu', 'data_code' =>'kivu', 'parent_data_code' =>'nyaruguru' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Ngera', 'data_code' =>'ngera', 'parent_data_code' =>'nyaruguru' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Ngoma', 'data_code' =>'ngoma', 'parent_data_code' =>'nyaruguru' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Nyabimata', 'data_code' =>'nyabimata', 'parent_data_code' =>'nyaruguru' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Nyagisozi', 'data_code' =>'nyagisozi', 'parent_data_code' =>'nyaruguru' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Muganza', 'data_code' =>'muganza', 'parent_data_code' =>'nyaruguru' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Ruheru', 'data_code' =>'ruheru', 'parent_data_code' =>'nyaruguru' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Ruramba', 'data_code' =>'ruramba', 'parent_data_code' =>'nyaruguru' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rusenge', 'data_code' =>'rusenge', 'parent_data_code' =>'nyaruguru' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],

			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kinazi', 'data_code' =>'kinazi', 'parent_data_code' =>'ruhango' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Byimana', 'data_code' =>'byimana', 'parent_data_code' =>'ruhango' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kinihira', 'data_code' =>'kinihira', 'parent_data_code' =>'ruhango' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Bweramana,', 'data_code' =>'bweramana,', 'parent_data_code' =>'ruhango' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Mbuye', 'data_code' =>'mbuye', 'parent_data_code' =>'ruhango' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Ruhango', 'data_code' =>'ruhango', 'parent_data_code' =>'ruhango' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Mwendo', 'data_code' =>'mwendo', 'parent_data_code' =>'ruhango' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kabagali', 'data_code' =>'kabagali', 'parent_data_code' =>'ruhango' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Ntongwe', 'data_code' =>'ntongwe', 'parent_data_code' =>'ruhango' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],

			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kimihurura', 'data_code' =>'kimihurura', 'parent_data_code' =>'gasabo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kacyiru', 'data_code' =>'kacyiru', 'parent_data_code' =>'gasabo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Remera', 'data_code' =>'remera', 'parent_data_code' =>'gasabo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kimironko', 'data_code' =>'kimironko', 'parent_data_code' =>'gasabo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Jali', 'data_code' =>'jali', 'parent_data_code' =>'gasabo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Jabana', 'data_code' =>'jabana', 'parent_data_code' =>'gasabo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rusororo', 'data_code' =>'rusororo', 'parent_data_code' =>'gasabo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Gisozi', 'data_code' =>'gisozi', 'parent_data_code' =>'gasabo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Bumbogo', 'data_code' =>'bumbogo', 'parent_data_code' =>'gasabo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Gatsata', 'data_code' =>'gatsata', 'parent_data_code' =>'gasabo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Gikomero', 'data_code' =>'gikomero', 'parent_data_code' =>'gasabo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Ndera', 'data_code' =>'ndera', 'parent_data_code' =>'gasabo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kinyinya', 'data_code' =>'kinyinya', 'parent_data_code' =>'gasabo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Nduba', 'data_code' =>'nduba', 'parent_data_code' =>'gasabo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rutunga', 'data_code' =>'rutunga', 'parent_data_code' =>'gasabo' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],

			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kicukiro', 'data_code' =>'kicukiro', 'parent_data_code' =>'kicukiro' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Niboye', 'data_code' =>'niboye', 'parent_data_code' =>'kicukiro' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kagarama', 'data_code' =>'kagarama', 'parent_data_code' =>'kicukiro' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Gatenga', 'data_code' =>'gatenga', 'parent_data_code' =>'kicukiro' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Gikondo', 'data_code' =>'gikondo', 'parent_data_code' =>'kicukiro' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kanombe', 'data_code' =>'kanombe', 'parent_data_code' =>'kicukiro' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Nyarugunga', 'data_code' =>'nyarugunga', 'parent_data_code' =>'kicukiro' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kigarama', 'data_code' =>'kigarama', 'parent_data_code' =>'kicukiro' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Masaka', 'data_code' =>'masaka', 'parent_data_code' =>'kicukiro' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],

			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kigali', 'data_code' =>'kigali', 'parent_data_code' =>'nyarugenge' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Gitega', 'data_code' =>'gitega', 'parent_data_code' =>'nyarugenge' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kanyinya', 'data_code' =>'kanyinya', 'parent_data_code' =>'nyarugenge' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Kimisagara', 'data_code' =>'kimisagara', 'parent_data_code' =>'nyarugenge' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Mageragere', 'data_code' =>'mageragere', 'parent_data_code' =>'nyarugenge' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Nyakabanda', 'data_code' =>'nyakabanda', 'parent_data_code' =>'nyarugenge' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Muhima', 'data_code' =>'muhima', 'parent_data_code' =>'nyarugenge' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Nyamirambo', 'data_code' =>'nyamirambo', 'parent_data_code' =>'nyarugenge' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Nyarugenge', 'data_code' =>'nyarugenge', 'parent_data_code' =>'nyarugenge' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],
			['country _code' => 'RWA', 'data_key' => 'sector', 'data_value' =>'Rwezamenyo', 'data_code' =>'rwezamenyo', 'parent_data_code' =>'nyarugenge' , 'status' => 'enabled' ,'data_type' =>'common', 'created_at' =>$created_at ],

			// Territory
			['country_code' => $country_code, 'data_key' => 'territory', 'data_value' => 'Eastern Territory', 'data_code' => 'eastern', 'parent_data_code' => 'province', 'status' => 'enabled', 'data_type' => 'common', 'created_at' => $created_at ],
			['country_code' => $country_code, 'data_key' => 'territory', 'data_value' => 'Western Territory', 'data_code' => 'western', 'parent_data_code' => 'province', 'status' => 'enabled', 'data_type' => 'common', 'created_at' => $created_at ],
			['country_code' => $country_code, 'data_key' => 'territory', 'data_value' => 'Northern Territory', 'data_code' => 'northern', 'parent_data_code' => 'province', 'status' => 'enabled', 'data_type' => 'common', 'created_at' => $created_at ],
			['country_code' => $country_code, 'data_key' => 'territory', 'data_value' => 'Southern Territory', 'data_code' => 'southern', 'parent_data_code' => 'province', 'status' => 'enabled', 'data_type' => 'common', 'created_at' => $created_at ],
			['country_code' => $country_code, 'data_key' => 'territory', 'data_value' => 'Kigali Territory', 'data_code' => 'kigali', 'parent_data_code' => 'province', 'status' => 'enabled', 'data_type' => 'common', 'created_at' => $created_at ],

			// Location
			['country_code' => $country_code, 'data_key' => 'location', 'data_value' => 'Location 1', 'data_code' => 'location_1', 'parent_data_code' => null, 'status' => 'enabled', 'data_type' => 'common', 'created_at' => $created_at ],
			['country_code' => $country_code, 'data_key' => 'location', 'data_value' => 'Location 2', 'data_code' => 'location_2', 'parent_data_code' => null, 'status' => 'enabled', 'data_type' => 'common', 'created_at' => $created_at ],
			['country_code' => $country_code, 'data_key' => 'location', 'data_value' => 'Location 3', 'data_code' => 'location_3', 'parent_data_code' => null, 'status' => 'enabled', 'data_type' => 'common', 'created_at' => $created_at ],
			['country_code' => $country_code, 'data_key' => 'location', 'data_value' => 'Location 4', 'data_code' => 'location_4', 'parent_data_code' => null, 'status' => 'enabled', 'data_type' => 'common', 'created_at' => $created_at ],
			['country_code' => $country_code, 'data_key' => 'location', 'data_value' => 'Location 5', 'data_code' => 'location_5', 'parent_data_code' => null, 'status' => 'enabled', 'data_type' => 'common', 'created_at' => $created_at ],
		]);
	}
}
