<?php
namespace Database\Seeders;
use DB;
use Illuminate\Database\Seeder;

class RolePrivSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {

       DB::table('app_role_privileges')->truncate();

        DB::table('app_role_privileges')->insert([													
            
          													
['role_code' => 'super_admin','priv_code' => 'data_key/create' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'app_support','priv_code' => 'data_key/create' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'data_key/create' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'data_key/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'app_support','priv_code' => 'data_key/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'data_key/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'data_key/edit' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'app_support','priv_code' => 'data_key/edit' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'data_key/edit' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'master_data/create' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'app_support','priv_code' => 'master_data/create' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'master_data/create' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'master_data/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'app_support','priv_code' => 'master_data/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'master_data/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'master_data/edit' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'app_support','priv_code' => 'master_data/edit' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'master_data/edit' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'addr_fields/create_view_edit_list' , 'status' => 'enabled', 'created_by' => 'seed'],											['role_code' => 'it_admin','priv_code' => 'addr_fields/create_view_edit_list' , 'status' => 'enabled', 'created_by' => 'seed'],		
													
['role_code' => 'super_admin','priv_code' => 'market/create' , 'status' => 'enabled', 'created_by' => 'seed'],											['role_code' => 'it_admin','priv_code' => 'market/create' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'market/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'app_support','priv_code' => 'market/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'market/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'market/edit' , 'status' => 'enabled', 'created_by' => 'seed'],											['role_code' => 'it_admin','priv_code' => 'market/edit' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'data_prvdr/create' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'data_prvdr/create' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'data_prvdr/create' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'it_admin','priv_code' => 'data_prvdr/create' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'data_prvdr/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'data_prvdr/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'data_prvdr/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],						['role_code' => 'operations_auditor','priv_code' => 'data_prvdr/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'app_support','priv_code' => 'data_prvdr/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'risk_compl_officer','priv_code' => 'data_prvdr/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'it_admin','priv_code' => 'data_prvdr/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'data_prvdr/edit' , 'status' => 'enabled', 'created_by' => 'seed'],											['role_code' => 'it_admin','priv_code' => 'data_prvdr/edit' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'data_prvdr/create_account' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'data_prvdr/create_account' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'data_prvdr/create_account' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'it_admin','priv_code' => 'data_prvdr/create_account' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'data_prvdr/list_account' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'data_prvdr/list_account' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'data_prvdr/list_account' , 'status' => 'enabled', 'created_by' => 'seed'],							['role_code' => 'app_support','priv_code' => 'data_prvdr/list_account' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'data_prvdr/list_account' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'data_prvdr/view_acc_txn' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'data_prvdr/view_acc_txn' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'data_prvdr/view_acc_txn' , 'status' => 'enabled', 'created_by' => 'seed'],							['role_code' => 'app_support','priv_code' => 'data_prvdr/view_acc_txn' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'data_prvdr/view_acc_txn' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'lender/create' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'lender/create' , 'status' => 'enabled', 'created_by' => 'seed'],										['role_code' => 'it_admin','priv_code' => 'lender/create' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'lender/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'lender/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],								['role_code' => 'app_support','priv_code' => 'lender/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'lender/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'lender/edit' , 'status' => 'enabled', 'created_by' => 'seed'],											['role_code' => 'it_admin','priv_code' => 'lender/edit' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'lender/create_account' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'lender/create_account' , 'status' => 'enabled', 'created_by' => 'seed'],										['role_code' => 'it_admin','priv_code' => 'lender/create_account' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'lender/list_account' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'lender/list_account' , 'status' => 'enabled', 'created_by' => 'seed'],								['role_code' => 'app_support','priv_code' => 'lender/list_account' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'lender/list_account' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'acc_prvdr/create' , 'status' => 'enabled', 'created_by' => 'seed'],											['role_code' => 'it_admin','priv_code' => 'acc_prvdr/create' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'acc_prvdr/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'acc_prvdr/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],								['role_code' => 'app_support','priv_code' => 'acc_prvdr/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'acc_prvdr/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'acc_prvdr/edit' , 'status' => 'enabled', 'created_by' => 'seed'],											['role_code' => 'it_admin','priv_code' => 'acc_prvdr/edit' , 'status' => 'enabled', 'created_by' => 'seed'],		
													
['role_code' => 'super_admin','priv_code' => 'customer/create' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'customer/create' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'customer/create' , 'status' => 'enabled', 'created_by' => 'seed'],						['role_code' => 'operations_auditor','priv_code' => 'customer/create' , 'status' => 'enabled', 'created_by' => 'seed'],			['role_code' => 'it_admin','priv_code' => 'customer/create' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'customer/search_list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'customer/search_list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'customer/search_list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'customer_success','priv_code' => 'customer/search_list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'customer_success_officer','priv_code' => 'customer/search_list_view' , 'status' => 'enabled', 'created_by' => 'seed'],			['role_code' => 'rm_support','priv_code' => 'customer/search_list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'operations_auditor','priv_code' => 'customer/search_list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'app_support','priv_code' => 'customer/search_list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'risk_compl_officer','priv_code' => 'customer/search_list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'it_admin','priv_code' => 'customer/search_list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'rms_external','priv_code' => 'customer/search_list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'investor','priv_code' => 'customer/search_list_view' , 'status' => 'enabled', 'created_by' => 'seed'],
['role_code' => 'super_admin','priv_code' => 'customer/edit' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'customer/edit' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'customer/edit' , 'status' => 'enabled', 'created_by' => 'seed'],						['role_code' => 'operations_auditor','priv_code' => 'customer/edit' , 'status' => 'enabled', 'created_by' => 'seed'],			['role_code' => 'it_admin','priv_code' => 'customer/edit' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'customer/create_account' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'customer/create_account' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'customer/create_account' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'it_admin','priv_code' => 'customer/create_account' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'customer/list_account' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'customer/list_account' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'customer/list_account' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'customer_success','priv_code' => 'customer/list_account' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'customer_success_officer','priv_code' => 'customer/list_account' , 'status' => 'enabled', 'created_by' => 'seed'],			['role_code' => 'rm_support','priv_code' => 'customer/list_account' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'operations_auditor','priv_code' => 'customer/list_account' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'app_support','priv_code' => 'customer/list_account' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'risk_compl_officer','priv_code' => 'customer/list_account' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'it_admin','priv_code' => 'customer/list_account' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'investor','priv_code' => 'customer/list_account' , 'status' => 'enabled', 'created_by' => 'seed'],
['role_code' => 'super_admin','priv_code' => 'customer/view_acc_txn' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'customer/view_acc_txn' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'customer/view_acc_txn' , 'status' => 'enabled', 'created_by' => 'seed'],					['role_code' => 'rm_support','priv_code' => 'customer/view_acc_txn' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'app_support','priv_code' => 'customer/view_acc_txn' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'customer/view_acc_txn' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'investor','priv_code' => 'customer/view_acc_txn' , 'status' => 'enabled', 'created_by' => 'seed'],
['role_code' => 'super_admin','priv_code' => 'customer/bring_to_probation' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'customer/bring_to_probation' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'customer/bring_to_probation' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'it_admin','priv_code' => 'customer/bring_to_probation' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'customer/close' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'customer/close' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'customer/close' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'it_admin','priv_code' => 'customer/close' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'customer/risk_category' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'customer/risk_category' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'customer/risk_category' , 'status' => 'enabled', 'created_by' => 'seed'],						['role_code' => 'operations_auditor','priv_code' => 'customer/risk_category' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'risk_compl_officer','priv_code' => 'customer/risk_category' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'it_admin','priv_code' => 'customer/risk_category' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'customer/active_cust_wo_fa' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'ops_admin','priv_code' => 'customer/active_cust_wo_fa' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'customer_success','priv_code' => 'customer/active_cust_wo_fa' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'customer_success_officer','priv_code' => 'customer/active_cust_wo_fa' , 'status' => 'enabled', 'created_by' => 'seed'],			['role_code' => 'rm_support','priv_code' => 'customer/active_cust_wo_fa' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'operations_auditor','priv_code' => 'customer/active_cust_wo_fa' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'risk_compl_officer','priv_code' => 'customer/active_cust_wo_fa' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'it_admin','priv_code' => 'customer/active_cust_wo_fa' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'rms_external','priv_code' => 'customer/active_cust_wo_fa' , 'status' => 'enabled', 'created_by' => 'seed'],	
['role_code' => 'super_admin','priv_code' => 'customer/cust_app_access' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'app_support','priv_code' => 'customer/cust_app_access' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'customer/cust_app_access' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'customer/perform_kyc' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'customer/perform_kyc' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'customer/perform_kyc' , 'status' => 'enabled', 'created_by' => 'seed'],						['role_code' => 'operations_auditor','priv_code' => 'customer/perform_kyc' , 'status' => 'enabled', 'created_by' => 'seed'],			['role_code' => 'it_admin','priv_code' => 'customer/perform_kyc' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'flow_rel_mgr/create' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'flow_rel_mgr/create' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'flow_rel_mgr/create' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'it_admin','priv_code' => 'flow_rel_mgr/create' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'flow_rel_mgr/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'flow_rel_mgr/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'flow_rel_mgr/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],					['role_code' => 'rm_support','priv_code' => 'flow_rel_mgr/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'operations_auditor','priv_code' => 'flow_rel_mgr/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'app_support','priv_code' => 'flow_rel_mgr/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'risk_compl_officer','priv_code' => 'flow_rel_mgr/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'it_admin','priv_code' => 'flow_rel_mgr/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'flow_rel_mgr/edit' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'flow_rel_mgr/edit' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'flow_rel_mgr/edit' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'it_admin','priv_code' => 'flow_rel_mgr/edit' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'data_prvdr_rel_mgr/create' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'data_prvdr_rel_mgr/create' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'data_prvdr_rel_mgr/create' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'it_admin','priv_code' => 'data_prvdr_rel_mgr/create' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'data_prvdr_rel_mgr/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'data_prvdr_rel_mgr/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'data_prvdr_rel_mgr/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],						['role_code' => 'operations_auditor','priv_code' => 'data_prvdr_rel_mgr/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'app_support','priv_code' => 'data_prvdr_rel_mgr/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'risk_compl_officer','priv_code' => 'data_prvdr_rel_mgr/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'it_admin','priv_code' => 'data_prvdr_rel_mgr/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'data_prvdr_rel_mgr/edit' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'data_prvdr_rel_mgr/edit' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'data_prvdr_rel_mgr/edit' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'it_admin','priv_code' => 'data_prvdr_rel_mgr/edit' , 'status' => 'enabled', 'created_by' => 'seed'],		
													
['role_code' => 'super_admin','priv_code' => 'product/create' , 'status' => 'enabled', 'created_by' => 'seed'],											['role_code' => 'it_admin','priv_code' => 'product/create' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'product/view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'product/view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'product/view' , 'status' => 'enabled', 'created_by' => 'seed'],						['role_code' => 'operations_auditor','priv_code' => 'product/view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'app_support','priv_code' => 'product/view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'risk_compl_officer','priv_code' => 'product/view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'it_admin','priv_code' => 'product/view' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'product/edit' , 'status' => 'enabled', 'created_by' => 'seed'],											['role_code' => 'it_admin','priv_code' => 'product/edit' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'product/search_list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'product/search_list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'product/search_list_view' , 'status' => 'enabled', 'created_by' => 'seed'],						['role_code' => 'operations_auditor','priv_code' => 'product/search_list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'app_support','priv_code' => 'product/search_list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'risk_compl_officer','priv_code' => 'product/search_list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'it_admin','priv_code' => 'product/search_list_view' , 'status' => 'enabled', 'created_by' => 'seed'],		
													
['role_code' => 'super_admin','priv_code' => 'application/apply' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'application/apply' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'application/apply' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'customer_success','priv_code' => 'application/apply' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'customer_success_officer','priv_code' => 'application/apply' , 'status' => 'enabled', 'created_by' => 'seed'],					['role_code' => 'app_support','priv_code' => 'application/apply' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'application/apply' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'application/search_list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'application/search_list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'application/search_list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'customer_success','priv_code' => 'application/search_list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'customer_success_officer','priv_code' => 'application/search_list_view' , 'status' => 'enabled', 'created_by' => 'seed'],					['role_code' => 'app_support','priv_code' => 'application/search_list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'risk_compl_officer','priv_code' => 'application/search_list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'it_admin','priv_code' => 'application/search_list_view' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'application/cancel' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'application/cancel' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'application/cancel' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'customer_success','priv_code' => 'application/cancel' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'customer_success_officer','priv_code' => 'application/cancel' , 'status' => 'enabled', 'created_by' => 'seed'],					['role_code' => 'app_support','priv_code' => 'application/cancel' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'application/cancel' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'application/approval' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'application/approval' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'application/approval' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'it_admin','priv_code' => 'application/approval' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'application/list_pre_appr' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'application/list_pre_appr' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'application/list_pre_appr' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'it_admin','priv_code' => 'application/list_pre_appr' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'application/delayed_approval_list' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'application/delayed_approval_list' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'application/delayed_approval_list' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'customer_success','priv_code' => 'application/delayed_approval_list' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'customer_success_officer','priv_code' => 'application/delayed_approval_list' , 'status' => 'enabled', 'created_by' => 'seed'],					['role_code' => 'app_support','priv_code' => 'application/delayed_approval_list' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'application/delayed_approval_list' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'loan/disburse' , 'status' => 'enabled', 'created_by' => 'seed'],											['role_code' => 'it_admin','priv_code' => 'loan/disburse' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'loan/home_capture_disbursal' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'loan/home_capture_disbursal' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'loan/home_capture_disbursal' , 'status' => 'enabled', 'created_by' => 'seed'],							['role_code' => 'app_support','priv_code' => 'loan/home_capture_disbursal' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'loan/home_capture_disbursal' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'loan/view_fa_capture_disbursal' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'loan/view_fa_capture_disbursal' , 'status' => 'enabled', 'created_by' => 'seed'],								['role_code' => 'app_support','priv_code' => 'loan/view_fa_capture_disbursal' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'loan/view_fa_capture_disbursal' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'loan/hold_loan_list' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'loan/hold_loan_list' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'loan/hold_loan_list' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'customer_success','priv_code' => 'loan/hold_loan_list' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'customer_success_officer','priv_code' => 'loan/hold_loan_list' , 'status' => 'enabled', 'created_by' => 'seed'],					['role_code' => 'app_support','priv_code' => 'loan/hold_loan_list' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'loan/hold_loan_list' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'loan/pending_confirmation_list' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'loan/pending_confirmation_list' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'loan/pending_confirmation_list' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'customer_success','priv_code' => 'loan/pending_confirmation_list' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'customer_success_officer','priv_code' => 'loan/pending_confirmation_list' , 'status' => 'enabled', 'created_by' => 'seed'],					['role_code' => 'app_support','priv_code' => 'loan/pending_confirmation_list' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'loan/pending_confirmation_list' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'loan/retry_disbursal' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'app_support','priv_code' => 'loan/retry_disbursal' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'loan/retry_disbursal' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'loan/penalize' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'loan/penalize' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'loan/penalize' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'it_admin','priv_code' => 'loan/penalize' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'loan/waive' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'ops_admin','priv_code' => 'loan/waive' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'it_admin','priv_code' => 'loan/waive' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'loan/release' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'loan/release' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'loan/release' , 'status' => 'enabled', 'created_by' => 'seed'],							['role_code' => 'app_support','priv_code' => 'loan/release' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'loan/release' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'loan/approve_part_payment' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'loan/approve_part_payment' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'loan/approve_part_payment' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'it_admin','priv_code' => 'loan/approve_part_payment' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'loan/capture_part_payment' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'loan/capture_part_payment' , 'status' => 'enabled', 'created_by' => 'seed'],								['role_code' => 'app_support','priv_code' => 'loan/capture_part_payment' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'loan/capture_part_payment' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'loan/capture_repayment' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'loan/capture_repayment' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'customer_success','priv_code' => 'loan/capture_repayment' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'customer_success_officer','priv_code' => 'loan/capture_repayment' , 'status' => 'enabled', 'created_by' => 'seed'],					['role_code' => 'app_support','priv_code' => 'loan/capture_repayment' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'loan/capture_repayment' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'loan/capture_excess' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'loan/capture_excess' , 'status' => 'enabled', 'created_by' => 'seed'],								['role_code' => 'app_support','priv_code' => 'loan/capture_excess' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'loan/capture_excess' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'loan/capture_repayment_new' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'loan/capture_repayment_new' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'loan/capture_repayment_new' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'customer_success','priv_code' => 'loan/capture_repayment_new' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'customer_success_officer','priv_code' => 'loan/capture_repayment_new' , 'status' => 'enabled', 'created_by' => 'seed'],					['role_code' => 'app_support','priv_code' => 'loan/capture_repayment_new' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'loan/capture_repayment_new' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'loan/unlink_payment' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'loan/unlink_payment' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'loan/unlink_payment' , 'status' => 'enabled', 'created_by' => 'seed'],							['role_code' => 'app_support','priv_code' => 'loan/unlink_payment' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'loan/unlink_payment' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'loan/search_list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'loan/search_list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'loan/search_list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'customer_success','priv_code' => 'loan/search_list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'customer_success_officer','priv_code' => 'loan/search_list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'recovery_specialist','priv_code' => 'loan/search_list_view' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'rm_support','priv_code' => 'loan/search_list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'operations_auditor','priv_code' => 'loan/search_list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'app_support','priv_code' => 'loan/search_list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'risk_compl_officer','priv_code' => 'loan/search_list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'it_admin','priv_code' => 'loan/search_list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'rms_external','priv_code' => 'loan/search_list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'investor','priv_code' => 'loan/search_list_view' , 'status' => 'enabled', 'created_by' => 'seed'],
['role_code' => 'super_admin','priv_code' => 'loan/request_write_off' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'loan/request_write_off' , 'status' => 'enabled', 'created_by' => 'seed'],								['role_code' => 'app_support','priv_code' => 'loan/request_write_off' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'loan/request_write_off' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'loan/approve_write_off' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'app_support','priv_code' => 'loan/approve_write_off' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'loan/approve_write_off' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'loan/search_list_view_write_off' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'loan/search_list_view_write_off' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'loan/search_list_view_write_off' , 'status' => 'enabled', 'created_by' => 'seed'],							['role_code' => 'app_support','priv_code' => 'loan/search_list_view_write_off' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'loan/search_list_view_write_off' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'loan/review_sync' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'loan/review_sync' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'loan/review_sync' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'customer_success','priv_code' => 'loan/review_sync' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'customer_success_officer','priv_code' => 'loan/review_sync' , 'status' => 'enabled', 'created_by' => 'seed'],					['role_code' => 'app_support','priv_code' => 'loan/review_sync' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'loan/review_sync' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'loan/recovery_list' , 'status' => 'enabled', 'created_by' => 'seed'],					['role_code' => 'recovery_specialist','priv_code' => 'loan/recovery_list' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'rm_support','priv_code' => 'loan/recovery_list' , 'status' => 'enabled', 'created_by' => 'seed'],				['role_code' => 'it_admin','priv_code' => 'loan/recovery_list' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'loan/capture_recovery' , 'status' => 'enabled', 'created_by' => 'seed'],					['role_code' => 'recovery_specialist','priv_code' => 'loan/capture_recovery' , 'status' => 'enabled', 'created_by' => 'seed'],						['role_code' => 'it_admin','priv_code' => 'loan/capture_recovery' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'loan/reverse_payment' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'app_support','priv_code' => 'loan/reverse_payment' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'loan/reverse_payment' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'loan/skip_txn_id_check' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'app_support','priv_code' => 'loan/skip_txn_id_check' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'loan/skip_txn_id_check' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'loan/disburse_manually' , 'status' => 'enabled', 'created_by' => 'seed'],			['role_code' => 'customer_success','priv_code' => 'loan/disburse_manually' , 'status' => 'enabled', 'created_by' => 'seed'],						['role_code' => 'app_support','priv_code' => 'loan/disburse_manually' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'loan/disburse_manually' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'loan/upgrade_requests' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'loan/upgrade_requests' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'loan/upgrade_requests' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'it_admin','priv_code' => 'loan/upgrade_requests' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'loan/home_screen_cancel_btn' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'loan/home_screen_cancel_btn' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'loan/home_screen_cancel_btn' , 'status' => 'enabled', 'created_by' => 'seed'],							['role_code' => 'app_support','priv_code' => 'loan/home_screen_cancel_btn' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'loan/home_screen_cancel_btn' , 'status' => 'enabled', 'created_by' => 'seed'],		
													
['role_code' => 'super_admin','priv_code' => 'email_report/daily_due_loans' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'email_report/daily_due_loans' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'email_report/daily_due_loans' , 'status' => 'enabled', 'created_by' => 'seed'],					['role_code' => 'rm_support','priv_code' => 'email_report/daily_due_loans' , 'status' => 'enabled', 'created_by' => 'seed'],				['role_code' => 'it_admin','priv_code' => 'email_report/daily_due_loans' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'report/portfolio_quality' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'report/portfolio_quality' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'report/portfolio_quality' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'it_admin','priv_code' => 'report/portfolio_quality' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'investor','priv_code' => 'report/portfolio_quality' , 'status' => 'enabled', 'created_by' => 'seed'],
['role_code' => 'super_admin','priv_code' => 'report/growth_chart' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'report/growth_chart' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'report/growth_chart' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'it_admin','priv_code' => 'report/growth_chart' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'investor','priv_code' => 'report/growth_chart' , 'status' => 'enabled', 'created_by' => 'seed'],
['role_code' => 'super_admin','priv_code' => 'report/product_takeup' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'report/product_takeup' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'report/product_takeup' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'it_admin','priv_code' => 'report/product_takeup' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'report/daily_activity' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'report/daily_activity' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'report/daily_activity' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'customer_success','priv_code' => 'report/daily_activity' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'customer_success_officer','priv_code' => 'report/daily_activity' , 'status' => 'enabled', 'created_by' => 'seed'],				['role_code' => 'operations_auditor','priv_code' => 'report/daily_activity' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'risk_compl_officer','priv_code' => 'report/daily_activity' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'it_admin','priv_code' => 'report/daily_activity' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'report/daily_activity_admin' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'report/daily_activity_admin' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'report/daily_activity_admin' , 'status' => 'enabled', 'created_by' => 'seed'],						['role_code' => 'operations_auditor','priv_code' => 'report/daily_activity_admin' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'risk_compl_officer','priv_code' => 'report/daily_activity_admin' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'it_admin','priv_code' => 'report/daily_activity_admin' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'mgmt/live_dashboard' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'mgmt/live_dashboard' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'mgmt/live_dashboard' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'it_admin','priv_code' => 'mgmt/live_dashboard' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'investor','priv_code' => 'mgmt/live_dashboard' , 'status' => 'enabled', 'created_by' => 'seed'],
['role_code' => 'super_admin','priv_code' => 'mgmt/monthly_dashboard' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'mgmt/monthly_dashboard' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'mgmt/monthly_dashboard' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'it_admin','priv_code' => 'mgmt/monthly_dashboard' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'investor','priv_code' => 'mgmt/monthly_dashboard' , 'status' => 'enabled', 'created_by' => 'seed'],
['role_code' => 'super_admin','priv_code' => 'mgmt/charts' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'mgmt/charts' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'mgmt/charts' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'it_admin','priv_code' => 'mgmt/charts' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'investor','priv_code' => 'mgmt/charts' , 'status' => 'enabled', 'created_by' => 'seed'],
['role_code' => 'super_admin','priv_code' => 'report/capital_funds' , 'status' => 'enabled', 'created_by' => 'seed'],											['role_code' => 'it_admin','priv_code' => 'report/capital_funds' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'report/rm_weekly_report' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'report/rm_weekly_report' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'report/rm_weekly_report' , 'status' => 'enabled', 'created_by' => 'seed'],						['role_code' => 'operations_auditor','priv_code' => 'report/rm_weekly_report' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'risk_compl_officer','priv_code' => 'report/rm_weekly_report' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'it_admin','priv_code' => 'report/rm_weekly_report' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'report/rm_report' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'report/rm_report' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'report/rm_report' , 'status' => 'enabled', 'created_by' => 'seed'],						['role_code' => 'operations_auditor','priv_code' => 'report/rm_report' , 'status' => 'enabled', 'created_by' => 'seed'],			['role_code' => 'it_admin','priv_code' => 'report/rm_report' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'report/sms_report' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'app_support','priv_code' => 'report/sms_report' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'report/sms_report' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'report/risk_portfolio' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'report/risk_portfolio' , 'status' => 'enabled', 'created_by' => 'seed'],							['role_code' => 'operations_auditor','priv_code' => 'report/risk_portfolio' , 'status' => 'enabled', 'created_by' => 'seed'],			['role_code' => 'it_admin','priv_code' => 'report/risk_portfolio' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'report/cust_performance' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'report/cust_performance' , 'status' => 'enabled', 'created_by' => 'seed'],										['role_code' => 'it_admin','priv_code' => 'report/cust_performance' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'report/os_advance' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'report/os_advance' , 'status' => 'enabled', 'created_by' => 'seed'],										['role_code' => 'it_admin','priv_code' => 'report/os_advance' , 'status' => 'enabled', 'created_by' => 'seed'],		
													
['role_code' => 'super_admin','priv_code' => 'score/create' , 'status' => 'enabled', 'created_by' => 'seed'],											['role_code' => 'it_admin','priv_code' => 'score/create' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'score/list' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'app_support','priv_code' => 'score/list' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'score/list' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'score/weightage_list' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'app_support','priv_code' => 'score/weightage_list' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'score/weightage_list' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'score/weightage_create' , 'status' => 'enabled', 'created_by' => 'seed'],											['role_code' => 'it_admin','priv_code' => 'score/weightage_create' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'score/weightage_edit' , 'status' => 'enabled', 'created_by' => 'seed'],											['role_code' => 'it_admin','priv_code' => 'score/weightage_edit' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'score/result_config_list' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'app_support','priv_code' => 'score/result_config_list' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'score/result_config_list' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'score/result_config_create_edit' , 'status' => 'enabled', 'created_by' => 'seed'],											['role_code' => 'it_admin','priv_code' => 'score/result_config_create_edit' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'score/factor_list' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'app_support','priv_code' => 'score/factor_list' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'score/factor_list' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'score/cust_txn' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'score/cust_txn' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'score/cust_txn' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'it_admin','priv_code' => 'score/cust_txn' , 'status' => 'enabled', 'created_by' => 'seed'],		
													
['role_code' => 'super_admin','priv_code' => 'master_agreement/create' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'master_agreement/create' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'master_agreement/create' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'it_admin','priv_code' => 'master_agreement/create' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'master_agreement/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'master_agreement/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'master_agreement/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],						['role_code' => 'operations_auditor','priv_code' => 'master_agreement/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'app_support','priv_code' => 'master_agreement/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'risk_compl_officer','priv_code' => 'master_agreement/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'it_admin','priv_code' => 'master_agreement/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],		
		['role_code' => 'ops_admin','priv_code' => 'cust_agreement/expired_list' , 'status' => 'enabled', 'created_by' => 'seed'],							['role_code' => 'app_support','priv_code' => 'cust_agreement/expired_list' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'cust_agreement/expired_list' , 'status' => 'enabled', 'created_by' => 'seed'],		
													
['role_code' => 'super_admin','priv_code' => 'recon/search' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'recon/search' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'recon/search' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'customer_success','priv_code' => 'recon/search' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'customer_success_officer','priv_code' => 'recon/search' , 'status' => 'enabled', 'created_by' => 'seed'],			['role_code' => 'rm_support','priv_code' => 'recon/search' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'operations_auditor','priv_code' => 'recon/search' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'app_support','priv_code' => 'recon/search' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'risk_compl_officer','priv_code' => 'recon/search' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'it_admin','priv_code' => 'recon/search' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'recon/recon_status' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'recon/recon_status' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'recon/recon_status' , 'status' => 'enabled', 'created_by' => 'seed'],					['role_code' => 'rm_support','priv_code' => 'recon/recon_status' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'operations_auditor','priv_code' => 'recon/recon_status' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'app_support','priv_code' => 'recon/recon_status' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'risk_compl_officer','priv_code' => 'recon/recon_status' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'it_admin','priv_code' => 'recon/recon_status' , 'status' => 'enabled', 'created_by' => 'seed'],		
									['role_code' => 'app_support','priv_code' => 'recon/reinitiate_recon' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'recon/reinitiate_recon' , 'status' => 'enabled', 'created_by' => 'seed'],		
									['role_code' => 'app_support','priv_code' => 'FIELD VISIT' , 'status' => 'enabled', 'created_by' => 'seed'],				
			['role_code' => 'customer_success','priv_code' => 'field_visit/self_search' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'customer_success_officer','priv_code' => 'field_visit/self_search' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'recovery_specialist','priv_code' => 'field_visit/self_search' , 'status' => 'enabled', 'created_by' => 'seed'],								
['role_code' => 'super_admin','priv_code' => 'field_visit/all_search' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'field_visit/all_search' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'field_visit/all_search' , 'status' => 'enabled', 'created_by' => 'seed'],					['role_code' => 'rm_support','priv_code' => 'field_visit/all_search' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'operations_auditor','priv_code' => 'field_visit/all_search' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'app_support','priv_code' => 'field_visit/all_search' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'risk_compl_officer','priv_code' => 'field_visit/all_search' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'it_admin','priv_code' => 'field_visit/all_search' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'field_visit/checkin' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'field_visit/checkin' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'field_visit/checkin' , 'status' => 'enabled', 'created_by' => 'seed'],			['role_code' => 'recovery_specialist','priv_code' => 'field_visit/checkin' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'relationship_manager','priv_code' => 'field_visit/checkin' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'rm_support','priv_code' => 'field_visit/checkin' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'operations_auditor','priv_code' => 'field_visit/checkin' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'risk_compl_officer','priv_code' => 'field_visit/checkin' , 'status' => 'enabled', 'created_by' => 'seed'],			
['role_code' => 'super_admin','priv_code' => 'field_visit/allow_force_checkin' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'field_visit/allow_force_checkin' , 'status' => 'enabled', 'created_by' => 'seed'],								['role_code' => 'app_support','priv_code' => 'field_visit/allow_force_checkin' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'field_visit/allow_force_checkin' , 'status' => 'enabled', 'created_by' => 'seed'],		
													
			['role_code' => 'customer_success','priv_code' => 'call_log/self_search' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'customer_success_officer','priv_code' => 'call_log/self_search' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'recovery_specialist','priv_code' => 'call_log/self_search' , 'status' => 'enabled', 'created_by' => 'seed'],			['role_code' => 'operations_auditor','priv_code' => 'call_log/self_search' , 'status' => 'enabled', 'created_by' => 'seed'],					
['role_code' => 'super_admin','priv_code' => 'call_log/all_search' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'call_log/all_search' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'call_log/all_search' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'customer_success','priv_code' => 'call_log/all_search' , 'status' => 'enabled', 'created_by' => 'seed'],				['role_code' => 'rm_support','priv_code' => 'call_log/all_search' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'operations_auditor','priv_code' => 'call_log/all_search' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'app_support','priv_code' => 'call_log/all_search' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'risk_compl_officer','priv_code' => 'call_log/all_search' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'it_admin','priv_code' => 'call_log/all_search' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'call_log/post' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'call_log/post' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'call_log/post' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'customer_success','priv_code' => 'call_log/post' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'customer_success_officer','priv_code' => 'call_log/post' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'recovery_specialist','priv_code' => 'call_log/post' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'rm_support','priv_code' => 'call_log/post' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'operations_auditor','priv_code' => 'call_log/post' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'risk_compl_officer','priv_code' => 'call_log/post' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'it_admin','priv_code' => 'call_log/post' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'rms_external','priv_code' => 'call_log/post' , 'status' => 'enabled', 'created_by' => 'seed'],	
													
['role_code' => 'super_admin','priv_code' => 'user/create' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'user/create' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'user/create' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'it_admin','priv_code' => 'user/create' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'user/edit' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'user/edit' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'user/edit' , 'status' => 'enabled', 'created_by' => 'seed'],									['role_code' => 'it_admin','priv_code' => 'user/edit' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'user/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'user/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'user/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],						['role_code' => 'operations_auditor','priv_code' => 'user/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'app_support','priv_code' => 'user/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'user/list_view' , 'status' => 'enabled', 'created_by' => 'seed'],		
													
['role_code' => 'super_admin','priv_code' => 'lead/audit_kyc' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'lead/audit_kyc' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'lead/audit_kyc' , 'status' => 'enabled', 'created_by' => 'seed'],						['role_code' => 'operations_auditor','priv_code' => 'lead/audit_kyc' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'app_support','priv_code' => 'lead/audit_kyc' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'lead/audit_kyc' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'lead/search' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'lead/search' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'lead/search' , 'status' => 'enabled', 'created_by' => 'seed'],						['role_code' => 'operations_auditor','priv_code' => 'lead/search' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'app_support','priv_code' => 'lead/search' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'risk_compl_officer','priv_code' => 'lead/search' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'it_admin','priv_code' => 'lead/search' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'lead/edit' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'lead/edit' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'lead/edit' , 'status' => 'enabled', 'created_by' => 'seed'],						['role_code' => 'operations_auditor','priv_code' => 'lead/edit' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'risk_compl_officer','priv_code' => 'lead/edit' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'it_admin','priv_code' => 'lead/edit' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'lead/create' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'lead/create' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'lead/create' , 'status' => 'enabled', 'created_by' => 'seed'],						['role_code' => 'operations_auditor','priv_code' => 'lead/create' , 'status' => 'enabled', 'created_by' => 'seed'],			['role_code' => 'it_admin','priv_code' => 'lead/create' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'lead/allow_manual_capture' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'lead/allow_manual_capture' , 'status' => 'enabled', 'created_by' => 'seed'],								['role_code' => 'app_support','priv_code' => 'lead/allow_manual_capture' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'lead/allow_manual_capture' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'statement/unknown_txns' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'statement/unknown_txns' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'statement/unknown_txns' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'customer_success','priv_code' => 'statement/unknown_txns' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'customer_success_officer','priv_code' => 'statement/unknown_txns' , 'status' => 'enabled', 'created_by' => 'seed'],					['role_code' => 'app_support','priv_code' => 'statement/unknown_txns' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'statement/unknown_txns' , 'status' => 'enabled', 'created_by' => 'seed'],		
									['role_code' => 'app_support','priv_code' => 'stmt_imports/search' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'stmt_imports/search' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'home/shortcuts' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'home/shortcuts' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'home/shortcuts' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'customer_success','priv_code' => 'home/shortcuts' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'customer_success_officer','priv_code' => 'home/shortcuts' , 'status' => 'enabled', 'created_by' => 'seed'],							['role_code' => 'it_admin','priv_code' => 'home/shortcuts' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'home/quick_access' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'home/quick_access' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'home/quick_access' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'customer_success','priv_code' => 'home/quick_access' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'customer_success_officer','priv_code' => 'home/quick_access' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'recovery_specialist','priv_code' => 'home/quick_access' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'rm_support','priv_code' => 'home/quick_access' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'operations_auditor','priv_code' => 'home/quick_access' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'risk_compl_officer','priv_code' => 'home/quick_access' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'it_admin','priv_code' => 'home/quick_access' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'rms_external','priv_code' => 'home/quick_access' , 'status' => 'enabled', 'created_by' => 'seed'],	
['role_code' => 'super_admin','priv_code' => 'rm_mgnt/rm_target' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'rm_mgnt/rm_target' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'rm_mgnt/rm_target' , 'status' => 'enabled', 'created_by' => 'seed'],							['role_code' => 'app_support','priv_code' => 'rm_mgnt/rm_target' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'rm_mgnt/rm_target' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'rm_mgnt/rm_assign' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'rm_mgnt/rm_assign' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'rm_mgnt/rm_assign' , 'status' => 'enabled', 'created_by' => 'seed'],							['role_code' => 'app_support','priv_code' => 'rm_mgnt/rm_assign' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'rm_mgnt/rm_assign' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'biz_ops/reports' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'biz_ops/reports' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'biz_ops/reports' , 'status' => 'enabled', 'created_by' => 'seed'],							['role_code' => 'app_support','priv_code' => 'biz_ops/reports' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'biz_ops/reports' , 'status' => 'enabled', 'created_by' => 'seed'],		
		['role_code' => 'ops_admin','priv_code' => 'account/third_party_owner' , 'status' => 'enabled', 'created_by' => 'seed'],								['role_code' => 'risk_compl_officer','priv_code' => 'account/third_party_owner' , 'status' => 'enabled', 'created_by' => 'seed'],			
		['role_code' => 'ops_admin','priv_code' => 'account/allow_tp_nid_manual_capture' , 'status' => 'enabled', 'created_by' => 'seed'],							['role_code' => 'app_support','priv_code' => 'account/allow_tp_nid_manual_capture' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'risk_compl_officer','priv_code' => 'account/allow_tp_nid_manual_capture' , 'status' => 'enabled', 'created_by' => 'seed'],			
			['role_code' => 'customer_success','priv_code' => 'cs_mgnt/cs_rosters' , 'status' => 'enabled', 'created_by' => 'seed'],										
['role_code' => 'super_admin','priv_code' => 'recon/manual_capture_txns' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'recon/manual_capture_txns' , 'status' => 'enabled', 'created_by' => 'seed'],								['role_code' => 'app_support','priv_code' => 'recon/manual_capture_txns' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'recon/manual_capture_txns' , 'status' => 'enabled', 'created_by' => 'seed'],		
									['role_code' => 'app_support','priv_code' => 'lead/bypass_audit_name' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'lead/bypass_audit_name' , 'status' => 'enabled', 'created_by' => 'seed'],		
									['role_code' => 'app_support','priv_code' => 'account/configure_btn' , 'status' => 'enabled', 'created_by' => 'seed'],				
['role_code' => 'super_admin','priv_code' => 'cust/raised_complaints' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'cust/raised_complaints' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'cust/raised_complaints' , 'status' => 'enabled', 'created_by' => 'seed'],							['role_code' => 'app_support','priv_code' => 'cust/raised_complaints' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'cust/raised_complaints' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'recon/add_stmt' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'recon/add_stmt' , 'status' => 'enabled', 'created_by' => 'seed'],								['role_code' => 'app_support','priv_code' => 'recon/add_stmt' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'recon/add_stmt' , 'status' => 'enabled', 'created_by' => 'seed'],		
['role_code' => 'super_admin','priv_code' => 'biz_ops/live_dashboard' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'market_admin','priv_code' => 'biz_ops/live_dashboard' , 'status' => 'enabled', 'created_by' => 'seed'],	['role_code' => 'ops_admin','priv_code' => 'biz_ops/live_dashboard' , 'status' => 'enabled', 'created_by' => 'seed'],							['role_code' => 'app_support','priv_code' => 'biz_ops/live_dashboard' , 'status' => 'enabled', 'created_by' => 'seed'],		['role_code' => 'it_admin','priv_code' => 'biz_ops/live_dashboard' , 'status' => 'enabled', 'created_by' => 'seed'],			

        ]);

    }
}
